# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54ab6bf1a4e96f1f11af144ca1a1b9c4c91f5d8d3a4b1705c22c62cec654c3061136aea0bd8387f8e06c0a89229a2e1ae785dde40dc2201ae4d8050d48c29175

test:
  secret_key_base: 702d11e00a139f11e581225f163ac12ef3d99c65b730d007c1ee2b80020b6d4227d96014fe515c0071bdd03211f27df23fb367e4175fa820b0c0e76545de7c23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
